name: Bug report
description: Report a bug to help us improve the project
title: "[Bug]: "
labels: bug
body:
- type: textarea
  attributes:
    label: Current Behavior
    placeholder: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    placeholder: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    placeholder: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  id: terms
  attributes:
    options:
      - label: I agree to follow this project's [Code of Conduct](https://github.com/rabraghib/.github/blob/main/CODE_OF_CONDUCT.md)
        required: true
