name: Feature request
description: Suggest an idea for this project
title: "[Feat]: "
labels: enhancement
body:
- type: textarea
  attributes:
    label: About the feature 
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    placeholder: |
      Make sure you well describe:
       - the problem/context
       - the solution you want to happen
       - Alternatives considered
       - ...and any valuable info to know
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct & Existing issues?
    options:
    - label: I have searched the existing issues
      required: true
    - label: I agree to follow this project's [Code of Conduct](https://github.com/rabraghib/.github/blob/main/CODE_OF_CONDUCT.md)
      required: true
