
name: Feature request
description: Suggest an idea for this project
title: "[Feat]: "
labels: enhancement
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    placeholder: |
      Make sure you well describe:
       - the problem/context
       - the solution you want to happen
       - Alternatives considered
       - ...and any valuable info to know
  validations:
    required: true
